version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: 'dev'
      PORT: 8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: